//
// This file is generated by parsec-rdl-gen (development version)
// WILL NOT be auto-generated if file has already existed.
//
package com.yahoo.ec;

import java.util.concurrent.CompletableFuture;
import com.yahoo.ec.parsec_generated.ResourceException;
import com.yahoo.ec.parsec_generated.Student;
import com.yahoo.ec.parsec_generated.Course;


public interface CurriculumClient {

    CompletableFuture<Course> getCourse(String studentId) throws ResourceException;
    CompletableFuture<String> postCourse(Course user) throws ResourceException;
}
