//
// This file is generated by parsec-rdl-gen (development version)
// WILL NOT be auto-generated if file has already existed.
//
package com.yahoo.ec;

import java.util.concurrent.CompletableFuture;
import com.yahoo.ec.parsec_generated.ResourceException;
import com.yahoo.ec.parsec_generated.Student;
import com.yahoo.ec.parsec_generated.Course;
import com.yahoo.ec.parsec_generated.CoursesResponse;


public interface CurriculumClient {

    CompletableFuture<CoursesResponse> getCoursesResponse(String studentId) throws ResourceException;
    CompletableFuture<Course> postCourse(Course course) throws ResourceException;
}
