//
// This file is generated by parsec-rdl-gen (development version)
// WILL NOT be auto-generated if file has already existed.
//
package yahoo.ec;

import java.util.concurrent.CompletableFuture;
import yahoo.ec.parsec_generated.ResourceException;
import yahoo.ec.parsec_generated.Student;


public interface CurriculumClient {

    CompletableFuture<Student> getStudent(int id) throws ResourceException;
}
